const Languages = {
  en:{
    'Flower Smart Water Meter':'Flower Smart Water Meter',
    'Sign In':'Sign In',
    'Enter your name':'Enter your name',
    'Enter your Phone Number':'Enter your Phone Number',
    'Enter your Email Address':'Enter your Email Address',
    'Collector Id':'Collector Id',
    'Meter Id':'Meter Id',
    'SUBMIT':'SUBMIT',
    'Login With OTP':'Login With OTP',
    'SEND':'SEND',
    'Sign Up':'Sign Up',
    'User Profile':'User Profile',
    'User':'User',
    'Name':'Name',
    'Mobile No':'Mobile No',
    'Mail Id':'Mail Id',
    'Log Out':'Log Out',
    'Home':'Home',
    'Add Meter':'Add Meter',
    'Buy Credit':'Buy Credit',
    'My Collector Id':'My Collector Id',
    'My Meter Id':'My Meter Id',
    'Meter Reading':'Meter Reading',
    'Balance Limit':'Balance Limit',
    'Battery Status':'Battery Status',
    'Interference':'Interference',
    'Current Reading':'Current Reading',
    'Current Balance':'Current Balance',
    'Credit':'Credit',
    'Calculate Payment':'Calculate Payment',
    'Payment':'Payment',
    'Purchase':'Purchase',
    'Dashboard':'Dashboard',
    'Read Meter':'Read Meter'
  },
  ar:{
    'Flower Smart Water Meter':'فلاور - عداد الماء الذكي',
    'Sign In':'الدخول',
    'Enter your name':'ادخل اسمك',
    'Enter your Phone Number':'ادخل رقم جوالك',
    'Enter your Email Address':'ادخل بريدك الإلكتروني',
    'Collector Id':'رقم جهاز التجميع',
    'Meter Id':'رقم العداد',
    'SUBMIT':'ارسال',
    'Login With OTP':'الدخول عن طريق رقم الجوال',
    'SEND':'ارسال',
    'Sign Up':'التسجيل',
    'User Profile':'معلومات المستخدم',
    'User':'المستخدم',
    'Name':'الإسم',
    'Mobile No':'رقم الجوال',
    'Mail Id':'البريد',
    'Log Out':'الخروج',
    'Home':'الرئيسية',
    'Add Meter':'إضافة عداد',
    'Buy Credit':'شراء رصيد',
    'My Collector Id':'رقم جهاز التجميع',
    'My Meter Id':'رقم العداد',
    'Meter Reading':'قراءة العداد',
    'Balance Limit':'الرصيد المتاح',
    'Battery Status':'حالة البطارية',
    'Interference':'التشويش',
    'Current Reading':'القراءة الحالية',
    'Current Balance':'الرصيد الحالي',
    'Credit':'الرصيد',
    'Calculate Payment':'احسب التسعيرة',
    'Payment':'الدفع',
    'Purchase':'الشراء',
    'Dashboard':'لوحة القيادة',
    'Read Meter':'قراءة العداد'
  }
}

export default Languages
